spring:
  application:
    name: texturepack-manager

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/texturepack_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: on-param
    include-binding-errors: on-param
    include-stacktrace: never
    include-exception: false


app:
  security:
    jwt:
      secret: ${JWT_SECRET:this-is-a-very-big-source-secret-key-ill-definitely-change-this-but-not-now}
      expiration: ${JWT_EXPIRATION:86400000}
  storage:
    path: ${STORAGE_LOCATION:./storage}